### ISSUE TITLE
can't get avro command to work

### ISSUE THREAD

**Issue by kmroz0991** [christiangalsterer/execbeat#13]
execbeat:

  commands:
    # Each - Commands to execute.
    -
      # Optional cron expression, defines when to execute the command.
      # Default is every 1 minute.
      #schedule:

      # The command to execute by Execbeat
      command: avro-tools

      # Optional arguments to be passed to the command to execute
      args: tojson /tmp/testfile.avro

      # Type to be published in the 'type' field. For Elasticsearch output,
      # the type defines the document type these entries should be stored
      # in. Default: execbeat
      #document_type:

.. out put:
"exec": {
    "command": "avro-tools",
    "exitCode": 0,
    "stdout": ""
  },
  "type": "execbeat

**Comment by kmroz0991** [comment]
"avro-tools tojson": executable file not found in $PATH

**Comment by christiangalsterer** [comment]
Which version do you use? Please note that there was a bug in 3.0.0 and earlier with multiple arguments which you may phase here. Can you please try 3.1.1?

**Comment by kmroz0991** [comment]
This was using 3.1.1

**Comment by christiangalsterer** [comment]
I can't reproduce this. I tried various combinations, specifying the command and args with and without double quotes in all cases it works for me.
