### ISSUE TITLE
Issue with schedule

### ISSUE THREAD

**Issue by rtaghawi** [christiangalsterer/execbeat#17]
I'm running powershell for counting active user, this is my Execbeat section which works fine, expect i enable (uncomment) schedule, than i get powershell error each seconds. 

############################## Execbeat ########################################
execbeat:

  commands:
    # Each - Commands to execute.
    -
      # Optional cron expression, defines when to execute the command.
      # Default is every 1 minute.
      #schedule: '* */5 * * * *' 

      # The command to execute by Execbeat
      command: powershell

      # Optional arguments to be passed to the command to execute
      args: "(get-aduser -property * -Filter {(enabled -eq $true)} ).count "

      # Type to be published in the 'type' field. For Elasticsearch output,
      # the type defines the document type these entries should be stored
      # in. Default: execbeat
      document_type: execbeat

#================================ General =====================================

**here is the result and errors after uncommenting the scedule line:**

PS C:\TMP\Elastic\execbeat-3.1.1-windows-x86> .\execbeat.exe -c .\execbeat.yml -e
2017/03/31 13:13:57.478460 beat.go:267: INFO Home path: [C:\TMP\Elastic\execbeat-3.1.1-windows-x86] Config path: [C:\TMP
\Elastic\execbeat-3.1.1-windows-x86] Data path: [C:\TMP\Elastic\execbeat-3.1.1-windows-x86\data] Logs path: [C:\TMP\Elas
tic\execbeat-3.1.1-windows-x86\logs]
2017/03/31 13:13:57.479461 beat.go:177: INFO Setup Beat: execbeat; Version: 3.1.1
2017/03/31 13:13:57.480461 output.go:167: INFO Loading template enabled. Reading template file: C:\TMP\Elastic\execbeat-
3.1.1-windows-x86\execbeat.template.json
2017/03/31 13:13:57.481460 output.go:178: INFO Loading template enabled for Elasticsearch 2.x. Reading template file: C:
\TMP\Elastic\execbeat-3.1.1-windows-x86\execbeat.template-es2x.json
2017/03/31 13:13:57.481460 client.go:120: INFO Elasticsearch url: http://localhost:9200
2017/03/31 13:13:57.482460 outputs.go:106: INFO Activated elasticsearch as output plugin.
2017/03/31 13:13:57.482460 publish.go:291: INFO Publisher name: ATWPIT01
2017/03/31 13:13:57.481460 logp.go:219: INFO Metrics logging every 30s
2017/03/31 13:13:57.486460 async.go:63: INFO Flush Interval set to: 1s
2017/03/31 13:13:57.486460 async.go:64: INFO Max Bulk Size set to: 50
2017/03/31 13:13:57.487461 beat.go:207: INFO execbeat start running.
2017/03/31 13:13:57.488461 execbeat.go:35: INFO execbeat is running! Hit CTRL-C to stop it.
2017/03/31 13:14:27.487565 logp.go:232: INFO No non-zero metrics in the last 30s
2017/03/31 13:14:57.487669 logp.go:232: INFO No non-zero metrics in the last 30s
**2017/03/31 13:15:04.905187 executor.go:88: ERR An error occured while executing command: exit status 1**
2017/03/31 13:15:05.491231 client.go:652: INFO Connected to Elasticsearch version 5.2.2
2017/03/31 13:15:05.491231 output.go:214: INFO Trying to load template for client: http://localhost:9200
2017/03/31 13:15:05.492231 output.go:235: INFO Template already exists and will not be overwritten.
**2017/03/31 13:15:05.829252 executor.go:88: ERR An error occured while executing command: exit status 1
2017/03/31 13:15:07.652380 executor.go:88: ERR An error occured while executing command: exit status 1
2017/03/31 13:15:07.653381 executor.go:88: ERR An error occured while executing command: exit status 1
2017/03/31 13:15:09.028476 executor.go:88: ERR An error occured while executing command: exit status 1
2017/03/31 13:15:11.308635 executor.go:88: ERR An error occured while executing command: exit status 1
2017/03/31 13:15:11.560655 executor.go:88: ERR An error occured while executing command: exit status 1
2017/03/31 13:15:11.926681 executor.go:88: ERR An error occured while executing command: exit status 1
2017/03/31 13:15:13.770809 executor.go:88: ERR An error occured while executing command: exit status 1
2017/03/31 13:15:15.648941 executor.go:88: ERR An error occured while executing command: exit status 1
2017/03/31 13:15:15.662941 executor.go:88: ERR An error occured while executing command: exit status 1**
2017/03/31 13:15:16.272984 logp.go:245: INFO Total non-zero values:  libbeat.es.published_and_acked_events=9 libbeat.pub
lisher.published_events=11 libbeat.es.publish.write_bytes=8487 libbeat.publisher.messages_in_worker_queues=11 libbeat.es
.call_count.PublishEvents=7 libbeat.es.publish.read_bytes=2789
2017/03/31 13:15:16.274985 logp.go:246: INFO Uptime: 1m18.7985263s
2017/03/31 13:15:16.275985 beat.go:211: INFO execbeat stopped.

**Comment by christiangalsterer** [comment]
I don't have access to a Windows machine, so I can't really test this. Which version do you use?

**Comment by christiangalsterer** [comment]
@rtaghawi, did you had a change to retest it again?
