### ISSUE TITLE
Flag Missed

### ISSUE THREAD

**Issue by zentola** [christiangalsterer/execbeat#21]
hi,

would be possible having the -strict.perms back again??
i am getting the error "flag provided but not defined: -strict.perms"

Thanks.

**Comment by christiangalsterer** [comment]
Hi,

not sure what you mean with "strict.perms". Can you please elaborate?

**Comment by zentola** [comment]
Hi Christian,
according elastic documentation:
https://www.elastic.co/guide/en/beats/libbeat/current/config-file-permissions.html
I was always using execbeat on my company, but on last version I'm getting this error and not able to launch execbeat.
I could disable strict.perms option on config, but this is highly recommended.

**Comment by zentola** [comment]
Hi Christian,
according elastic documentation:
https://www.elastic.co/guide/en/beats/libbeat/current/config-file-permissions.html
I was always using execbeat on my company, but on last version I'm getting this error and not able to launch execbeat.
I could disable strict.perms option on config, but this is highly recommended.
Thanks in advance.

**Comment by christiangalsterer** [comment]
This was introduced with Beats 5.3 but the current version of Execbeat is using 5.2.x. I'm currently preparing a new version 3.3.0 which will use Beats 5.6.2. and then the parameters should be back.

**Comment by zentola** [comment]
Ok, many thanks.
I will waiting for it. 
This issue appeared when I was industrializing last 5.6.0. Beats version. 
I didn't include execbeat on new beats package, but will include it again when it will be available.
many thanks for the support!

**Comment by christiangalsterer** [comment]
Execbeat 3.3.0 is just released.
