### ISSUE TITLE
RelativePath in "args" is not work,but AbsolutePath can do.

### ISSUE THREAD

**Issue by SwinBlackSea** [christiangalsterer/execbeat#23]
Hello,
    For a question , When I try to start execbeat by way of service in windows,I can't  get right result but "ERR An error occured while executing command: exit status 2" , then I change the style of args in execbeat.yml from RelativePath to AbsolutePath , I get the right result. example:
 [ schedule: 0/1 * * * * ?
      command: python
      args: ip.py/ 
]    "ERR An error occured while executing command: exit status 2" 
BUT
[schedule: 0/1 * * * * ?
      command: python
      args: D:\zork2.2.1\BDAgent\release\3rdPlugins\doubowen\testserver\ip.py
]    this way is right .I get right result.

the problem is that I must use RelativePath in my project .How can I do?
Thank you very much.

**Comment by christiangalsterer** [comment]
In the example with relativ path there is a backslash at the end.
Can you try the following options?:
args: .\ip.py\
args: ip.py

Can you check also the log files for more details and post the log output here.

**Comment by SwinBlackSea** [comment]
Thank you very much  christiangalsterer  ,due to I am in China so I received your retry latter.I'm sorry.
    follower is the log named execbeat:
        path:execbeat/log/execbeat
        comment:
           2017-09-08T17:16:20+08:00 ERR An error occured while executing command: exit status 2
           2017-09-08T17:16:20+08:00 INFO Execbeat%!(EXTRA string=Executing command: [%v], string=)
     but now I solved this problem by user the relative path such as: 
           args: "${path.config}/../../ip.py"    
     and ip.py in  "../../"  base on execbeat  path 
     it's very difficult for me to find the path ,however,with my friend help,I got it in execbeat.full.yml.
at the last,I want to share something:when  I user daemon to start execbeat ,no matter relative path or abs path .but when I use service to start execbeat by relative path ,maybe I should use the path above. 

Thank your replay , @christiangalsterer :+1:
