### ISSUE TITLE
beats library does not have Evebts anymore

### ISSUE THREAD

**Issue by gshamov** [christiangalsterer/execbeat#4]
Building execbeat fails as of today with the following error:

b.Events undefined (type *beat.Beat has no field or method Events).

It can be built with an old libbeats version (I have used glide.yaml of FLowbeat as described here https://discuss.elastic.co/t/flowbeats-fails-in-go-build/48601 to get an older libbeats). 

Should somehow dependencies get versioning in execbeat as well?

**Comment by christiangalsterer** [comment]
I'm currently traveling with access to a proper internet connection.

Dependency management was always a little bit tricky with go but u want to update to latest Go and libbeats versions anyway and had also plans to introduce glide. So please stay tuned and I hope I can provide an updated release in the next days.

**Comment by christiangalsterer** [comment]
Hi @gshamov,

 I managed to update to Go 1.6, libbeat 1.2.3, and glide for dependency management and local and travis build look fine.

I still want to do some cleanup due to the updates, but maybe you can give it a try already.

**Comment by christiangalsterer** [comment]
Version 1.1.0 released now using glide.
