### ISSUE TITLE
Logs not flushed to disk on windows

### ISSUE THREAD

**Issue by iamambrus** [christiangalsterer/execbeat#5]
I am using (the otherwise great!) execbeat on windows (server 2008 R2 standard) and see execbeat not flushing the file to disk properly (stalling for 3+ hours in my case now). I have a filebeat picking up execbeat's logs but it will force close the logfile if inactive for n seconds (which it definitely is).
Any thoughts? Perhaps [this](https://msdn.microsoft.com/en-us/library/windows/desktop/aa364451(v=vs.85).aspx) can help? Many thanks!
PS to be even more specific I can see the exebeat log file size change (grow), but the date modified shown by windows explorer stays the same

**Comment by christiangalsterer** [comment]
Unfortunately I don't have any windows machine available for testing, so this may get a little bit hard to reproduce.

The beat itself doesn't do anything itself with the logs but relies completely on the Elastic libbeat infrastructure.  You mentioned that the files size groups: Does the file contain output or is it empty?

**Comment by christiangalsterer** [comment]
Just another wild guess: When looking at https://www.elastic.co/support/matrix Windows 2008 is not really supported by Elastic. They provide a binary but don't support it.

**Comment by iamambrus** [comment]
Thanks @christiangalsterer. Yes this looks related to libbeat and could be specific to Windows / 2008, haven't experienced this issue on any other OS. File contents update but not the date time. Contents of file do get updated but not the date modified attribute, see [screenshot](https://www.evernote.com/l/ACYs_cE2pG1HhqS8W0oU5l8R2dDfuoh9YLA).
