### ISSUE TITLE
Multiple arguments are not properly passed to command

### ISSUE THREAD

**Issue by gitime** [christiangalsterer/execbeat#7]
Hi,

I use execbeat to execute my shellscript, which accept multiple arguments. I have my execbeat configuration like;

    execbeat:
      execs:
        -
          cron: "@every 5s"
          command: "/shellscripts/test.sh"
          args: "arga argb argc"
          document_type: execbeat
          fields:
            host: 192.168.0.1
            beatname: "beat1"
    output.console:
      enabled: true
      pretty: true

my scellscript is very simple, its like;

    #!/bin/sh
    echo $1

but my ecexbeat always outputs;

    arga argb argc

I am expecting only one output `arga`, how can I do this?

Thank you.

**Comment by christiangalsterer** [comment]
Hi
I just tested it and I think you found a bug.
Need to look into it how to fix it.

**Comment by christiangalsterer** [comment]
I have found the issue and will provide a release tomorrow.

**Comment by christiangalsterer** [comment]
Release 3.0.1 is now available.
