### ISSUE TITLE
Error in getting linux service status using bash command

### ISSUE THREAD

**Issue by usmanC9** [christiangalsterer/execbeat#8]
Hi ,
I am using execbeat to get status of my linux services. I am using "bash" command and in argument i am passing the service status command like this:

execbeat:
  commands:
    -
      schedule: "@every 10s"
      command: bash
      args: service execbeat status
      document_type: "service_status"
  
output.console:
      enabled: true
      pretty: true

execbeat output is :

  "exec": {
    "command": "bash",
    "stderr": "bash: service execbeat status: No such file or directory\n",
    "stdout": ""
  }

It is  expecting a file path in argument. 
How can I execute the bash command without passing file path as an argument ?

Thank You.

**Comment by christiangalsterer** [comment]
I think the following should work:
command: service
args: execbeat status

Can you give this a try?

**Comment by christiangalsterer** [comment]
I just tried it and it works when using the example from the previous comment

**Comment by christiangalsterer** [comment]
Please note to use version 3.0.1 (released today) as previous versions contained a bug when specifying  multiple args.

**Comment by usmanC9** [comment]
Thanks. its working. 
Now I want to get only **Active:** part of the the stdout. For this I am using this configuration:

execbeat:
commands:
-
schedule: "@every 10s"
command: service 
args: execbeat status | grep Active:
document_type: "service_status"

Execbeat giving me complete output of the service command.

"@timestamp": "2017-02-22T10:28:08.000Z",
  "exec": {
    "command": "service",
    "stdout": "● execbeat.service - execbeat\n   Loaded: loaded (/usr/lib/systemd/system/execbeat.service; disabled; vendor preset: disabled)\n   Active: active (running) since Wed 2017-02-22 05:27:08 EST; 59s ago\n     Docs: https://www.elastic.co/guide/en/beats/execbeat/current/index.html\n Main PID: 31976 (execbeat)\n   CGroup: /system.slice/execbeat.service\n           ├─31976 /usr/share/execbeat/bin/execbeat -c /etc/execbeat/execbeat.yml -path.home /usr/share/execbeat -path.config /etc/execbeat -path.data /var/lib/execbeat -path.logs /var/log/execbeat\n           ├─32399 /bin/sh /usr/sbin/service execbeat status | grep Active\n           ├─32410 /bin/bash /etc/init.d/execbeat status | grep Active\n           └─32416 systemctl status execbeat.service\n\nFeb 22 05:27:08 master-machine systemd[1]: Started execbeat.\nFeb 22 05:27:08 master-machine systemd[1]: Starting execbeat...\n"
  },
  "type": "service_status"
}

How can I grep only Active: part of the output.

Thank you.

**Comment by jautz** [comment]
@usmanC9: it seems you are running systemd so I am wondering if you might want to call systemctl directly. Also, instead of grep'ing the default output there are more script-friendly approaches: the following command will exit with code zero if the service is active:
```
systemctl --user --quiet is-active execbeat.service
```
