### ISSUE TITLE
Execbeat is not executing any command

### ISSUE THREAD

**Issue by gitime** [christiangalsterer/execbeat#9]
Hi,

I am using execbeat execbeat-5.2.1-SNAPSHOT-linux-x86_64 in my CentOS box. I have the configuration like below;

	execbeat:

	  execs:
		-
		  schedule: "@every 10s"
		  command: date
		  document_type: execbeat

	output.console:
	  enabled: true
	  pretty: true

when I execute this, I am gettting the below output;

	bash-4.1$ ./execbeat -c echotest.yml -e -d "*"
	2017/02/23 05:15:07.114313 beat.go:267: INFO Home path: [/execbeat/execbeat-5.2.1-SNAPSHOT-linux-x86_64] Config path: [/execbeat/execbeat-5.2.1-SNAPSHOT-linux-x86_64] Data path: [/execbeat/execbeat-5.2.1-SNAPSHOT-linux-x86_64/data] Logs path: [/execbeat/execbeat-5.2.1-SNAPSHOT-linux-x86_64/logs]
	2017/02/23 05:15:07.114347 beat.go:177: INFO Setup Beat: execbeat; Version: 3.0.1
	2017/02/23 05:15:07.114359 processor.go:43: DBG  Processors:
	2017/02/23 05:15:07.114371 beat.go:183: DBG  Initializing output plugins
	2017/02/23 05:15:07.114414 outputs.go:106: INFO Activated console as output plugin.
	2017/02/23 05:15:07.114426 publish.go:234: DBG  Create output worker
	2017/02/23 05:15:07.114471 publish.go:276: DBG  No output is defined to store the topology. The server fields might not be filled.
	2017/02/23 05:15:07.114497 publish.go:291: INFO Publisher name: mypc
	2017/02/23 05:15:07.114661 async.go:63: INFO Flush Interval set to: 1s
	2017/02/23 05:15:07.114673 async.go:64: INFO Max Bulk Size set to: 2048
	2017/02/23 05:15:07.114683 async.go:72: DBG  create bulk processing worker (interval=1s, bulk size=2048)
	2017/02/23 05:15:07.115033 logp.go:219: INFO Metrics logging every 30s
	2017/02/23 05:15:07.115193 beat.go:207: INFO execbeat start running.
	2017/02/23 05:15:07.115215 execbeat.go:35: INFO execbeat is running! Hit CTRL-C to stop it.
	2017/02/23 05:15:37.115192 logp.go:232: INFO No non-zero metrics in the last 30s
	2017/02/23 05:16:07.115270 logp.go:232: INFO No non-zero metrics in the last 30s
	^C2017/02/23 05:16:07.796883 service.go:32: DBG  Received sigterm/sigint, stopping
	2017/02/23 05:16:07.797013 logp.go:245: INFO Total non-zero values:
	2017/02/23 05:16:07.797028 logp.go:246: INFO Uptime: 1m0.686646585s
	2017/02/23 05:16:07.797034 beat.go:211: INFO execbeat stopped.

my command is not executing. Why is this happening?

**Comment by christiangalsterer** [comment]
Starting with 3.0.0 the configuration has changed.
Please rename "execs" to "commands" and it should work again.
```
execbeat:

  commands:
	-
	  schedule: "@every 10s"
	  command: date
	  document_type: execbeat
```

Unfortunately the documentation and the examples were only adjusted partially.

**Comment by LuisLoureiro** [comment]
The same problem was occurring with me.
I ended up here after searching a little bit.

After looking at your answer I noticed that the link "download" in the README file is pointing to a specific tag version, 2.1.1.

Can you update the README file?

Do you want a PR?

Regards,
_Luís Loureiro_

**Comment by christiangalsterer** [comment]
I will fix the README. Sorry for the confusion.

**Comment by LuisLoureiro** [comment]
Perfect. Thank you @christiangalsterer
